version: "3.9"

services:
  webclient:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ../:/utkusarioglu/utkusarioglu-com
      - ~/projects/utkusarioglu-root-ca:/utkusarioglu/utkusarioglu-com/.certs:ro
