version: "3.9"

services:
  webclient:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu/utkusarioglu-com
      - type: bind
        source: ~/projects/utkusarioglu-root-ca/p-256/server
        target: /utkusarioglu/utkusarioglu-com/.certs
        read_only: true
        volume:
          nocopy: true
