name: Sync to AWS S3 bucket

on:
  workflow_dispatch:

jobs:
  build-web-artifact:
    uses: ./.github/workflows/build-web.yml

  apply-aws-changes:
    needs: build-web-artifact
    name: Sync changes to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download web build artifact
        uses: actions/download-artifact@v2
        with:
          name: utkusarioglu-com-web-build
          path: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform
        run: |
          terraform -chdir=./.terraform init 
          terraform -chdir=./.terraform apply --auto-approve
