name: Build for web and upload as artifact
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    name: Build web version and upload as artifact
    runs-on: ubuntu-latest 
    environment: production
    container: 
      image: node:16-slim
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        id: Install
        run: yarn
      - name: Build
        id: build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: utkusarioglu-com-web-build
          path: build
