name: build-pdfs
on:
  # push:
  # branches:
  # - feature/resume-print
  workflow_dispatch:
  workflow_call:

jobs:
  build-website:
    uses: ./.github/workflows/build-website.yml
    secrets: inherit

  build-pdfs:
    needs:
      - build-website
    name: build-pdfs
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download web build artifact
        uses: actions/download-artifact@v2
        with:
          name: utkusarioglu-com-web-build
          path: build

      - name: Cache resume artifacts
        uses: actions/cache@v3
        id: resume-artifacts-cache
        with:
          path: .puppeteer/artifacts
          key: resume-artifacts-cache-${{ hashFiles('build' )}}
          restore-keys: |
            resume-artifacts-cache-

      - name: Generate server certificates
        if: steps.resume-artifacts-cache.outputs.cache-hit != 'true'
        uses: kofemann/action-create-certificate@v0.0.4
        with:
          hostcert: "chain.crt"
          hostkey: "tls.key"
          cachain: "ca.crt"

      - name: Move certificates
        if: steps.resume-artifacts-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .certs/server
          mv chain.crt .certs/server/
          mv tls.key .certs/server/
          mv ca.crt .certs/server/
          # This is done to please the pptruser: the user in 
          # puppeteer container.
          sudo chmod -R +r .certs

      - name: Add required packages
        run: |
          rm package.json
          yarn add http-server local-ssl-proxy \
            --frozen-lockfile \
            --non-interactive
          sudo apt install ghostscript -y

      - name: Run Puppeteer pdf creation
        if: steps.resume-artifacts-cache.outputs.cache-hit != 'true'
        env:
          CERTS_FOLDER: "${{ github.workspace }}/.certs"
        run: |
          sudo scripts/start-local-server.sh & \
            sudo scripts/docker-run-puppeteer-pdf.sh $CERTS_FOLDER

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: utkusarioglu-com-pdf-artifacts
          path: .puppeteer/artifacts
