name: Update Trucker Jokes Source
on:
  push:
    branches:
      - dev
    paths:
      - "public/trucker-jokes/**.txt"
  workflow_dispatch:

jobs:
  update-paper-chain:
    name: Update trucker jokes source
    runs-on: ubuntu-latest
    environment: production
    # container: node:16
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Publish to server
        id: publish
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/trucker-jokes/
          server-dir: ./domains/utkusarioglu.com/public_html/trucker-jokes/
          dangerous-clean-slate: true
